/**
 * Nationality options — the users.nationality column stores an ISO 3166-1 alpha-2
 * code (locale-independent), while the UI renders a localized country name. Shared
 * by the admin users edit form (OptionSelect) and its column filter (ColumnFilter)
 * so the stored code, the filter match and the displayed label never drift apart.
 */
export interface NationalityOption {
  /** ISO 3166-1 alpha-2 code — the value persisted on users.nationality. */
  code: string;
  en: string;
  zh: string;
}

export const NATIONALITIES: NationalityOption[] = [
  { code: "AF", en: "Afghanistan", zh: "阿富汗" },
  { code: "AL", en: "Albania", zh: "阿尔巴尼亚" },
  { code: "DZ", en: "Algeria", zh: "阿尔及利亚" },
  { code: "AD", en: "Andorra", zh: "安道尔" },
  { code: "AO", en: "Angola", zh: "安哥拉" },
  { code: "AG", en: "Antigua and Barbuda", zh: "安提瓜和巴布达" },
  { code: "AR", en: "Argentina", zh: "阿根廷" },
  { code: "AM", en: "Armenia", zh: "亚美尼亚" },
  { code: "AU", en: "Australia", zh: "澳大利亚" },
  { code: "AT", en: "Austria", zh: "奥地利" },
  { code: "AZ", en: "Azerbaijan", zh: "阿塞拜疆" },
  { code: "BS", en: "Bahamas", zh: "巴哈马" },
  { code: "BH", en: "Bahrain", zh: "巴林" },
  { code: "BD", en: "Bangladesh", zh: "孟加拉国" },
  { code: "BB", en: "Barbados", zh: "巴巴多斯" },
  { code: "BY", en: "Belarus", zh: "白俄罗斯" },
  { code: "BE", en: "Belgium", zh: "比利时" },
  { code: "BZ", en: "Belize", zh: "伯利兹" },
  { code: "BJ", en: "Benin", zh: "贝宁" },
  { code: "BT", en: "Bhutan", zh: "不丹" },
  { code: "BO", en: "Bolivia", zh: "玻利维亚" },
  { code: "BA", en: "Bosnia and Herzegovina", zh: "波斯尼亚和黑塞哥维那" },
  { code: "BW", en: "Botswana", zh: "博茨瓦纳" },
  { code: "BR", en: "Brazil", zh: "巴西" },
  { code: "BN", en: "Brunei", zh: "文莱" },
  { code: "BG", en: "Bulgaria", zh: "保加利亚" },
  { code: "BF", en: "Burkina Faso", zh: "布基纳法索" },
  { code: "BI", en: "Burundi", zh: "布隆迪" },
  { code: "CV", en: "Cabo Verde", zh: "佛得角" },
  { code: "KH", en: "Cambodia", zh: "柬埔寨" },
  { code: "CM", en: "Cameroon", zh: "喀麦隆" },
  { code: "CA", en: "Canada", zh: "加拿大" },
  { code: "CF", en: "Central African Republic", zh: "中非共和国" },
  { code: "TD", en: "Chad", zh: "乍得" },
  { code: "CL", en: "Chile", zh: "智利" },
  { code: "CN", en: "China", zh: "中国" },
  { code: "CO", en: "Colombia", zh: "哥伦比亚" },
  { code: "KM", en: "Comoros", zh: "科摩罗" },
  { code: "CR", en: "Costa Rica", zh: "哥斯达黎加" },
  { code: "CI", en: "Côte d'Ivoire", zh: "科特迪瓦" },
  { code: "HR", en: "Croatia", zh: "克罗地亚" },
  { code: "CU", en: "Cuba", zh: "古巴" },
  { code: "CY", en: "Cyprus", zh: "塞浦路斯" },
  { code: "CZ", en: "Czechia", zh: "捷克" },
  { code: "CD", en: "DR Congo", zh: "刚果（金）" },
  { code: "CG", en: "Republic of the Congo", zh: "刚果（布）" },
  { code: "DK", en: "Denmark", zh: "丹麦" },
  { code: "DJ", en: "Djibouti", zh: "吉布提" },
  { code: "DM", en: "Dominica", zh: "多米尼克" },
  { code: "DO", en: "Dominican Republic", zh: "多米尼加" },
  { code: "EC", en: "Ecuador", zh: "厄瓜多尔" },
  { code: "EG", en: "Egypt", zh: "埃及" },
  { code: "SV", en: "El Salvador", zh: "萨尔瓦多" },
  { code: "GQ", en: "Equatorial Guinea", zh: "赤道几内亚" },
  { code: "ER", en: "Eritrea", zh: "厄立特里亚" },
  { code: "EE", en: "Estonia", zh: "爱沙尼亚" },
  { code: "SZ", en: "Eswatini", zh: "埃斯瓦蒂尼" },
  { code: "ET", en: "Ethiopia", zh: "埃塞俄比亚" },
  { code: "FJ", en: "Fiji", zh: "斐济" },
  { code: "FI", en: "Finland", zh: "芬兰" },
  { code: "FR", en: "France", zh: "法国" },
  { code: "GA", en: "Gabon", zh: "加蓬" },
  { code: "GM", en: "Gambia", zh: "冈比亚" },
  { code: "GE", en: "Georgia", zh: "格鲁吉亚" },
  { code: "DE", en: "Germany", zh: "德国" },
  { code: "GH", en: "Ghana", zh: "加纳" },
  { code: "GR", en: "Greece", zh: "希腊" },
  { code: "GD", en: "Grenada", zh: "格林纳达" },
  { code: "GT", en: "Guatemala", zh: "危地马拉" },
  { code: "GN", en: "Guinea", zh: "几内亚" },
  { code: "GW", en: "Guinea-Bissau", zh: "几内亚比绍" },
  { code: "GY", en: "Guyana", zh: "圭亚那" },
  { code: "HT", en: "Haiti", zh: "海地" },
  { code: "HN", en: "Honduras", zh: "洪都拉斯" },
  { code: "HU", en: "Hungary", zh: "匈牙利" },
  { code: "IS", en: "Iceland", zh: "冰岛" },
  { code: "IN", en: "India", zh: "印度" },
  { code: "ID", en: "Indonesia", zh: "印度尼西亚" },
  { code: "IR", en: "Iran", zh: "伊朗" },
  { code: "IQ", en: "Iraq", zh: "伊拉克" },
  { code: "IE", en: "Ireland", zh: "爱尔兰" },
  { code: "IL", en: "Israel", zh: "以色列" },
  { code: "IT", en: "Italy", zh: "意大利" },
  { code: "JM", en: "Jamaica", zh: "牙买加" },
  { code: "JP", en: "Japan", zh: "日本" },
  { code: "JO", en: "Jordan", zh: "约旦" },
  { code: "KZ", en: "Kazakhstan", zh: "哈萨克斯坦" },
  { code: "KE", en: "Kenya", zh: "肯尼亚" },
  { code: "KI", en: "Kiribati", zh: "基里巴斯" },
  { code: "KP", en: "North Korea", zh: "朝鲜" },
  { code: "KR", en: "South Korea", zh: "韩国" },
  { code: "KW", en: "Kuwait", zh: "科威特" },
  { code: "KG", en: "Kyrgyzstan", zh: "吉尔吉斯斯坦" },
  { code: "LA", en: "Laos", zh: "老挝" },
  { code: "LV", en: "Latvia", zh: "拉脱维亚" },
  { code: "LB", en: "Lebanon", zh: "黎巴嫩" },
  { code: "LS", en: "Lesotho", zh: "莱索托" },
  { code: "LR", en: "Liberia", zh: "利比里亚" },
  { code: "LY", en: "Libya", zh: "利比亚" },
  { code: "LI", en: "Liechtenstein", zh: "列支敦士登" },
  { code: "LT", en: "Lithuania", zh: "立陶宛" },
  { code: "LU", en: "Luxembourg", zh: "卢森堡" },
  { code: "MG", en: "Madagascar", zh: "马达加斯加" },
  { code: "MW", en: "Malawi", zh: "马拉维" },
  { code: "MY", en: "Malaysia", zh: "马来西亚" },
  { code: "MV", en: "Maldives", zh: "马尔代夫" },
  { code: "ML", en: "Mali", zh: "马里" },
  { code: "MT", en: "Malta", zh: "马耳他" },
  { code: "MH", en: "Marshall Islands", zh: "马绍尔群岛" },
  { code: "MR", en: "Mauritania", zh: "毛里塔尼亚" },
  { code: "MU", en: "Mauritius", zh: "毛里求斯" },
  { code: "MX", en: "Mexico", zh: "墨西哥" },
  { code: "FM", en: "Micronesia", zh: "密克罗尼西亚" },
  { code: "MD", en: "Moldova", zh: "摩尔多瓦" },
  { code: "MC", en: "Monaco", zh: "摩纳哥" },
  { code: "MN", en: "Mongolia", zh: "蒙古" },
  { code: "ME", en: "Montenegro", zh: "黑山" },
  { code: "MA", en: "Morocco", zh: "摩洛哥" },
  { code: "MZ", en: "Mozambique", zh: "莫桑比克" },
  { code: "MM", en: "Myanmar", zh: "缅甸" },
  { code: "NA", en: "Namibia", zh: "纳米比亚" },
  { code: "NR", en: "Nauru", zh: "瑙鲁" },
  { code: "NP", en: "Nepal", zh: "尼泊尔" },
  { code: "NL", en: "Netherlands", zh: "荷兰" },
  { code: "NZ", en: "New Zealand", zh: "新西兰" },
  { code: "NI", en: "Nicaragua", zh: "尼加拉瓜" },
  { code: "NE", en: "Niger", zh: "尼日尔" },
  { code: "NG", en: "Nigeria", zh: "尼日利亚" },
  { code: "NO", en: "Norway", zh: "挪威" },
  { code: "OM", en: "Oman", zh: "阿曼" },
  { code: "PK", en: "Pakistan", zh: "巴基斯坦" },
  { code: "PW", en: "Palau", zh: "帕劳" },
  { code: "PS", en: "Palestine", zh: "巴勒斯坦" },
  { code: "PA", en: "Panama", zh: "巴拿马" },
  { code: "PG", en: "Papua New Guinea", zh: "巴布亚新几内亚" },
  { code: "PY", en: "Paraguay", zh: "巴拉圭" },
  { code: "PE", en: "Peru", zh: "秘鲁" },
  { code: "PH", en: "Philippines", zh: "菲律宾" },
  { code: "PL", en: "Poland", zh: "波兰" },
  { code: "PT", en: "Portugal", zh: "葡萄牙" },
  { code: "QA", en: "Qatar", zh: "卡塔尔" },
  { code: "RO", en: "Romania", zh: "罗马尼亚" },
  { code: "RU", en: "Russia", zh: "俄罗斯" },
  { code: "RW", en: "Rwanda", zh: "卢旺达" },
  { code: "LC", en: "Saint Lucia", zh: "圣卢西亚" },
  { code: "VC", en: "Saint Vincent and the Grenadines", zh: "圣文森特和格林纳丁斯" },
  { code: "WS", en: "Samoa", zh: "萨摩亚" },
  { code: "SM", en: "San Marino", zh: "圣马力诺" },
  { code: "ST", en: "São Tomé and Príncipe", zh: "圣多美和普林西比" },
  { code: "SA", en: "Saudi Arabia", zh: "沙特阿拉伯" },
  { code: "SN", en: "Senegal", zh: "塞内加尔" },
  { code: "RS", en: "Serbia", zh: "塞尔维亚" },
  { code: "SC", en: "Seychelles", zh: "塞舌尔" },
  { code: "SL", en: "Sierra Leone", zh: "塞拉利昂" },
  { code: "SG", en: "Singapore", zh: "新加坡" },
  { code: "SK", en: "Slovakia", zh: "斯洛伐克" },
  { code: "SI", en: "Slovenia", zh: "斯洛文尼亚" },
  { code: "SB", en: "Solomon Islands", zh: "所罗门群岛" },
  { code: "SO", en: "Somalia", zh: "索马里" },
  { code: "ZA", en: "South Africa", zh: "南非" },
  { code: "SS", en: "South Sudan", zh: "南苏丹" },
  { code: "ES", en: "Spain", zh: "西班牙" },
  { code: "LK", en: "Sri Lanka", zh: "斯里兰卡" },
  { code: "SD", en: "Sudan", zh: "苏丹" },
  { code: "SR", en: "Suriname", zh: "苏里南" },
  { code: "SE", en: "Sweden", zh: "瑞典" },
  { code: "CH", en: "Switzerland", zh: "瑞士" },
  { code: "SY", en: "Syria", zh: "叙利亚" },
  { code: "TW", en: "Taiwan, China", zh: "中国台湾" },
  { code: "TJ", en: "Tajikistan", zh: "塔吉克斯坦" },
  { code: "TZ", en: "Tanzania", zh: "坦桑尼亚" },
  { code: "TH", en: "Thailand", zh: "泰国" },
  { code: "TL", en: "Timor-Leste", zh: "东帝汶" },
  { code: "TG", en: "Togo", zh: "多哥" },
  { code: "TO", en: "Tonga", zh: "汤加" },
  { code: "TT", en: "Trinidad and Tobago", zh: "特立尼达和多巴哥" },
  { code: "TN", en: "Tunisia", zh: "突尼斯" },
  { code: "TR", en: "Türkiye", zh: "土耳其" },
  { code: "TM", en: "Turkmenistan", zh: "土库曼斯坦" },
  { code: "TV", en: "Tuvalu", zh: "图瓦卢" },
  { code: "UG", en: "Uganda", zh: "乌干达" },
  { code: "UA", en: "Ukraine", zh: "乌克兰" },
  { code: "AE", en: "United Arab Emirates", zh: "阿拉伯联合酋长国" },
  { code: "GB", en: "United Kingdom", zh: "英国" },
  { code: "US", en: "United States", zh: "美国" },
  { code: "UY", en: "Uruguay", zh: "乌拉圭" },
  { code: "UZ", en: "Uzbekistan", zh: "乌兹别克斯坦" },
  { code: "VU", en: "Vanuatu", zh: "瓦努阿图" },
  { code: "VA", en: "Vatican City", zh: "梵蒂冈" },
  { code: "VE", en: "Venezuela", zh: "委内瑞拉" },
  { code: "VN", en: "Vietnam", zh: "越南" },
  { code: "YE", en: "Yemen", zh: "也门" },
  { code: "ZM", en: "Zambia", zh: "赞比亚" },
  { code: "ZW", en: "Zimbabwe", zh: "津巴布韦" },
];

const BY_CODE: Record<string, NationalityOption> = Object.fromEntries(
  NATIONALITIES.map((n) => [n.code, n]),
);

/** Localized country name for a stored code. Unknown/legacy values fall back to
 *  the raw string so historical free-text rows still render instead of blanking. */
export function nationalityLabel(code: string | null | undefined, locale: string): string {
  if (!code) return "";
  const hit = BY_CODE[code.toUpperCase()];
  if (!hit) return code;
  return locale === "zh" ? hit.zh : hit.en;
}
